### ISSUE TITLE
Best optimization points

### ISSUE THREAD

**Issue by nwittler** [q-optimize/c3#139]
## Describe the missing feature
The `best_point.log` stored by during optimization procedures should be easily usable and human editable for reuse as initial points.

## Describe the solution you'd like
Replace the logging (and reading in) function to use `hjson` instead of `jjson` in the same fashion as config files.

## Describe alternatives you've considered
Create an editor for the files, which seems more involved.

**Comment by lazyoracle** [comment]
Can your log reader currently parse these files to make the pretty `rich` plots?

**Comment by nwittler** [comment]
> Can your log reader currently parse these files to make the pretty `rich` plots?

Yes.
