### ISSUE TITLE
The pauli_basis function in the qt_utils.py file only works for qubit dimensions up to three

### ISSUE THREAD

**Issue by MAN6O** [q-optimize/c3#16]
```
if nq == 1:
    op = op_tuple[0]
if nq == 2:
    op = np.kron(op_tuple[0], op_tuple[1])
if nq == 3:
    op = np.kron(np.kron(op_tuple[0], op_tuple[1]), op_tuple[2])
```

This should be solved by replacing the code above in the function by this general snippet:

```
op = op_tuple[0]
for i in range(nq-1):
       op = np.kron(op, op_tuple[i+1])
```

**Comment by lazyoracle** [comment]
Closed in #54

**Comment by shaimach** [comment]
If we need a function to generate the general SU(n) generators, I have one
in Matlab that we can translate.

**Comment by lazyoracle** [comment]
@nwittler @fedroy do we need SU(n) generators? In that case, we should track it in another issue and I can port the MATLAB code.
