### ISSUE TITLE
Question about "Entangling gate on two coupled qubits" example

### ISSUE THREAD

**Issue by vsandinh** [q-optimize/c3#175]
## Describe the question
The optimized parameters in the "Entangling gate on two coupled qubits" example  are of two Gaussian pulses for 2 qubits. This is not the most general way to guarantee that we will have the solution to the optimization. Were these parameters chosen instead of piece-wise-constant pulses because there are less parameters to optimize in the C2? How do we generalize this? For example, I am trying to optimize a different 2-qubit gate and the optimization doesn't converge.

**Comment by lazyoracle** [comment]
Hi @vsandinh, can you share a minimal working example or some more technical details and description of the gate you are trying to optimize which doesn't converge? That would help us understand the problem better.

**Comment by lazyoracle** [comment]
There is now an example showing optimization with piece-wise constant pulses. Closed in #202
