### ISSUE TITLE
Experiment.load_quick_setup can't handle files in not current directory 

### ISSUE THREAD

**Issue by picbeats** [q-optimize/c3#183]
## Describe the bug
Experiment.load_quick_setup loads a HJSON config file referencing files describing model and generator.
If overal config file (i.e. examples/qiskit.cfg) is not in a current directory, load fails

## To Reproduce
Move examples/*.cfg to examples/cfg/
change reference to qiskit.cfg to cfg/qiskit.cfg in examples/c3_qiskit.ipynb and try to run. 

## Expected behavior
Not absolute (not starting with /) file names in quick setup file must be treated as relative to the file itself.

## Environment (please complete the following information)
 - OS: [e.g. MacOS]
 - Python Version: [e.g. 3.8]
 - `c3-toolset` Version [e.g. 1.2]

## Additional context
Add any other context about the problem here. You can also suggest possible solutions and relevant implementations & edge case details.

**Comment by nwittler** [comment]
6bcdf77 closes this, right?
