### ISSUE TITLE
PWC pulse has incorrect dimensions

### ISSUE THREAD

**Issue by Ashutosh-Mishra2** [q-optimize/c3#201]
## Describe the bug
AWG returns a signal of shape (n, n) instead of (n, ). This causes error during computing the propagator.

## To Reproduce
Steps to reproduce the behavior. This can be in the form of a code snippet or some config files or a notebook to produce a minimum viable example of the bug.

## Expected behavior
AWG should return an (1D) array for the signal.

## Screenshots
![image](https://user-images.githubusercontent.com/61776089/168765491-9621c221-18a9-49a2-a38a-f185bf43d731.png)

## Environment (please complete the following information)
 - OS: Linux
 - Python Version: 3.8.13
 - `c3-toolset` dev branch, version 1.4

**Comment by Ashutosh-Mishra2** [comment]
I think this issue occurs as the shape of the pulse (from pwc_shape in envelopes.py) has shape (n, 1). And shape of mask (in _get_shape_values_just in pulse.py) is (n, ). Multiplying the mask to the pulse gives a shape of (n, n). 

Changing [len(t), 1]  (line 65, pwc_shape in envelop.py) to [len(t)] seems to work.

**Comment by nwittler** [comment]
Please add a config or script that produces the error.

**Comment by nwittler** [comment]
Can you add it in test form, so that #202 fails?
