### ISSUE TITLE
Missing line in 'Open-loop optimal control' docs

### ISSUE THREAD

**Issue by flo-maier** [q-optimize/c3#73]
**Describe the bug**
On readthedocs there is a line missing in the code which leads to 'ValueError: not enough values to unpack' (expected 2, got 0) (https://c3-toolset.readthedocs.io/en/latest/optimal_control.html) 

**To Reproduce**
1. Execute the code from Setup of a two-qubit chip with C3 and Open-loop optimal control on readthedocs
2. See error

**Expected behavior**
No error

**Screenshots**
![image](https://user-images.githubusercontent.com/80908258/111655650-1ea34880-880a-11eb-8e3e-52775503c679.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - PyCharm 2020.3.4
 - Anaconda 4.9.2 / Python 3.8.5

**Solution**
Add 'exp.pmap.set_opt_map(gateset_opt_map)' before 'opt.optimize_controls()'

**Comment by lazyoracle** [comment]
Closing because docs are consistent with current `dev`
