### ISSUE TITLE
Tests: C1 Robust requires update

### ISSUE THREAD

**Issue by lazyoracle** [q-optimize/c3#79]
**Describe the bug**
https://github.com/q-optimize/c3/blob/d571137fd9d155c36a4badd8c7e2f450b8610e37/test/test_noise.py#L229

**Comment by lazyoracle** [comment]
@nwittler Can you add more details to the issue description to list what needs to be updated in this test?

**Comment by GlaserN** [comment]
Fixed in 494c95183babfe9a40c0cfbe5cdd30e885edb5e9
